# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Soniczac7.DownloadManager
PackageVersion: 5.1.0.0
InstallerType: zip
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: DownloadManagerInstaller.exe
InstallerSwitches:
  Silent: --install
  SilentWithProgress: --install
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
- InstallerUrl: https://github.com/Download-Manager-Community/Download-Manager/releases/download/5.1.0.0/DownloadManagerInstallerUnpacked.zip
  Architecture: x64
  InstallerSha256: 60BDD92E928717BAB16E33047E517E35CB9250090162E27F62073034E3308474
ManifestType: installer
ManifestVersion: 1.6.0
